CSV Data Format for DTA Transfer
================================
Frank Hofmann
:subtitle:
:doctype: book
:copyright: Frank Hofmann
:revnumber: 1.0
:Author Initials: FH
:edition: 1
:lang: en
:date: 6. Aug 2015
:numbered:

== TA 826 (ISR payments) ==

[cols="1,5,2", options="header"]
|===
|Field id
|Description
|Value/Example

|#0
|transaction id
|`826`

|#1
|requested processing date
+
format: `YYMMDD` (see dta header structure for details)
|`131220` for December 20, 2013

|#2
|bank clearing number beneficiary (receiver)
|has to be empty

|#3
|output sequence number (processed by the bank)
|has to be empty

|===

* field id #4: creation date. Date when the data file was created. Has to be the same for all
  data records.

  format:	YYMMDD
  example:	131220 for December 20, 2013

* field id #5: bank clearing number order (sender)

  format:	xxxxxxx (seven characters)
  example:	ABC1234

* field id #6: data file sender identification
  The same identification hast to be included for all records.

  format:	xxxxx (five characters)
  example:	ABC12

* field id #7: entry sequence number

  has to be empty, will be added automatically

* field id #8: payment type

  value:	0

* field id #9: processing flag

  value:	0

* field id #10: ordering party identification (sender id)
  corresponds to dta id #20 part one

  format:	xxxxx (five characters)
  example:	ABC01

* field id #11: ordering party transaction number
  corresponds to dta id #20 part two

  format:	max. sixteen characters
  example:	fh-1567

* field id #12: account to be debited - with or without IBAN
  corresponds to dta id #25

  format:	twenty-four characters
  example:	CH930076201162123456

* field id #13: payment value date
  corresponds to dta id #32a part one

  has to be left empty

* field id #14: ISO currency code
  corresponds to dta id #32a part two

  value:	CHF

* field id #15: payment amount
  corresponds to dta id #32a part three

  format:	dd,dd (see dta spec for exact length)
  example:	123,45

* field id #16 to #19: ordering party line
  corresponds to dta id #50 

  format:	twenty characters

* field id #20: beneficiary party identification (ISR party number)
  corresponds to dta id #59 line 1 

  format:	twelve characters
  example:	/C/123456789

* field id #21 to #24: beneficiary party line 1 to 4
  name and address of the receiver
  corresponds to dta id #59 line 2 to 5 

  format:	twenty characters per line

* field id #25: isr reference number (reason for payment)
  corresponds to dta id #70

  format:	twenty-seven digits

* field id #26: isr check digit
  corresponds to dta id #70

  format:	two digits

Full example:
  
826;131220;;12345;131220;Bank 44;ABC12;;1;6;ABC01;12345678901;56789;;CHF;123,45;Felix Z;Markt 1;1234 Zürich;;/C/123456789;Hans Wurst;Taufgraben 1;1234 Bern;;1234567890123456;34


