Documentation for lib-dta-ch
============================
Frank Hofmann
:subtitle:
:doctype: book
:copyright: Frank Hofmann
:revnumber: 1.0
:Author Initials: FH
:edition: 1
:lang: en
:date: 10 Aug 2015
:numbered:

== About lib-dta-ch ==

lib-dta-ch is a PHP library to record bank transactions electronically,
and to prepare these transactions for automatic processing by Swiss
banks with the help of an standardized DTA record file. DTA is the
abbreviation for 'Datenträgeraustauschverfahren', and describes methods
to exchange data media between financial institutes, and its clients.

This library provides classes and methods to record both single and
multiple transactions, to validate, cumulate, and sort these records
according to the DTA specification from <<SIX, SIX Interbank Clearing>>.

== Authors and Copyright ==

(C) 2013-2015 Frank Hofmann, Berlin, Germany 

Email frank.hofmann@efho.de

Released under GNU Public License (GPL).

== Project Website and Updates ==

The library code is available from the lib-dta-ch project page at
GitHub:

https://github.com/hofmannedv/dta-ch

== How to use lib-dta-ch in your project ==

* import 'lib-dta-ch'


== DTA Support ==

Currently, these Swiss banks support DTA:

* <<http://www.bnpparibas.ch/, BNP Paribas>>

* <<http://www.raiffeisen.ch/, Raiffeisen Switzerland>>

In contrast, about 22 Cantonal banks use <<http://www.finnova.com/,
Finnova>>. ZKB, St. Galler KB and Luzerner KB are using core banking
system called <<http://www.avaloq.com/, Avaloq>>.

== Acknowledgements ==

Many thanks to Gerold Rupprecht <geroldr@bluewin.ch> for his support on
Swiss financial transactions.

== Links and References ==

We think the following resources are helpul for you:

[[[SIX]]]:: SIX Interbank Clearing, http://www.six-interbank-clearing.com/de/home.html

[[[DTAStandards]]]:: DTA: Standards und Formate (PDF), http://www.six-interbank-clearing.com/dam/downloads/de/standardization/dta/dta.pdf

[[[DTAPayments]]]:: DTA: Zahlungseinreichung an SIX Interbank Clearing (PDF), http://www.six-interbank-clearing.com/dam/downloads/de/standardization/dta/zahlungseinreichung.pdf


